# Generated by Django 5.2.5 on 2025-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='embedding',
            field=models.TextField(blank=True, help_text='Vector de embedding para búsqueda por similitud.', null=True),
        ),
    ]
