# Generated by Django 5.2.5 on 2025-08-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
