# Generated by Django 5.2.5 on 2025-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(help_text='La fila, representada con una letra (ej. A, B)', max_length=2),
        ),
    ]
